

export interface Card {
    id:number;
    name: string;
    img: string;
    img2: string;
    img3: string;
    video:string;
    technology:string;
    text: string;
    github: string;
    details: string;
  }

export const websites: Card[] = [
    { id: 1, name: 'My portfolio website', img: '../../../assets/img/websites/portfolio.jpg', img2:'../../../assets/img/websites/portfolio_small.jpg', img3:'../../../assets/img/websites/portfolio_mobile.jpg', video:'../../assets/img/websites/portfolio_demo.webm', technology:'Angular, SCSS, TypeScript', text: 'This is my portfolio website, which I designed in Adobe XD and then made it by using Angular framework. It is a summary of my up-to-date  work and the process of learning how to program. It is more clear and more orderly than my other projects. The experience of  writing  apps and websites taught  me how to write a more friendly code.<br><br> In this project I used Angular Animations for the first time. Before that, I was using only CSS keyframes or Anime.js. The website is responsive and written according to the mobile first standards.', github: 'https://github.com/MagiTom/Portfolio-Website', details: '#' },
    { id: 2, name: 'Galactic Clothing Shop', img: '../../../assets/img/websites/Galactic.jpg', img2:'../../assets/img/websites/Galactic_small.jpg', img3:'../../assets/img/websites/Galactic_mobile.jpg', video:'../../../assets/img/websites/galactic_demo.webm', technology:'Angular, SCSS, TypeScript', text: '<b>Warning!</b> This project is still open! Is not finished yet because it is being developed by three people. My part in this project is everything about the store (list of products, cart, summary of shopping) and login and sign up forms. I attached right services for that and made all validations using reactive forms.', github: 'https://github.com/MagiTom/Galactic-Clothing-Store', details: '#' },
    { id: 3, name: 'Website for pianist', img: '../../../assets/img/websites/pianist.jpg', img2:'../../assets/img/websites/pianist_s.jpg', img3:'../../assets/img/websites/pianist_s.jpg', video:'../../../assets/img/websites/pianist_demo.webm', technology:'Webpack, Saas, Javascript', text: 'This is website which I designed and made for my brother-in-law, but it is still not in use, because I want to rewrite it in my beloved Angular <i class="far fa-heart"></i> and maybe improve its apperance a bit. In this project I wanted to focus on webpack, scss and pure javascript. I wanted to have a website which is written without any frameworks and library. Website is responsive and written according to the mobile first standards.', github: 'https://github.com/MagiTom/Website-for-pianist', details: '#' },
    { id: 4, name: 'Guinea Pigs Farm', img: '../../../assets/img/pigs.png', img2:'../../assets/img/websites/pigs_small.png', img3:'../../assets/img/websites/pigs_mobile.png', video:'../../../assets/img/websites/pigs_demo.webm', technology:'Webpack, Saas, Javascript, Anime.js, Observer API', text: 'The small OnePage websites which I made to exercise Anime.js and Intersection Observer Api. It is written in webpack using html, scss and javascript. Website is responsive and written according to the mobile first standards.', github: 'https://github.com/MagiTom/Guinea-Pig-Farm-Web-AnimeJS-Observer-API', details: '#' },
    { id: 5, name: 'HOUSES BY THE LAKE', img: '../../../assets/img/websites/houses.png', img2:'../../assets/img/websites/houses_small.png', img3:'../../assets/img/websites/houses_mobile.png', video:'../../../assets/img/websites/houses_demo.webm', technology:'Bootstrap, Html, Css', text: 'OnePage website written with Bootstrap (using its layout and components), HTML and CSS.', github: 'https://github.com/MagiTom/Domki-nad-jeziorem', details: '#' },
  ];

  export const apps:Card[] = [
    { id: 6, name: 'My blog app', img: '../../../assets/img/blog.png', img2:'../../assets/img/apps/blog__small_s.png', img3:'../../../assets/img/blog_mobile.png', video:'../../../assets/img/apps/blog.webm', technology:'Angular, SCSS, TypeScript, Json-Server', text: 'Angular blog app where you can add, remove and update posts. In each of the posts you can add a random picture, write a title and add content. You can’t add an empty post or a post without a title. All of the posts are saved in a json-server, so you won’t lose your data. In the nav there is an icon with magnifier, which, when clicked on, will let you filter yours posts.', github: 'https://github.com/MagiTom/BlogApp', details: '#' },
    { id: 7, name: 'Ticket-reservation app', img: '../../../assets/img/apps/ticket.jpg', img2:'../../assets/img/apps/ticket_s.jpg', img3:'../../assets/img/apps/ticket_s.jpg', video:'../../../assets/img/apps/ticket.webm', technology:'Angular, Express.js, MongoDB, SCSS, TypeScript, Json-Server', text: 'It was my first experimental app made in Angular, so I am aware that it has a lot of imperfections in the code. But thanks to this project I learned a lot and I can avoid  a lot of bugs in the future. I began with making a server in express.js and connected it with MongoDB to have a possibility to login and signUp. Information about a flight is downloaded from api FlyScanner, but some information are set randomly, because api has not provided them for free. After you choose a place of departure, destination, date and number of people , you can see available  flights (only one flight per day). After clicking the button "choose" you proceed to the next step which is "choose luggage" and "choose seats" for passengers. The last step is the summary of your chosen options in this application. App is responsive and written according to the mobile first standards.<br><br> <b>Warning!</b> To try all functionality of this app, you have to clone this repository on your computer, because the back-end of the app stopped working on heroku.', github: 'https://github.com/MagiTom/Ticket-Plane-Booking-', details: '#' },
    { id: 8, name: 'My wallet', img: '../../../assets/img/apps/wallet.png', img2:'../../assets/img/apps/wallet_s.png', img3:'../../assets/img/apps/wallet_s.png', video:'../../../assets/img/apps/mywallet.webm', technology:'Javascript, OOP, CSS, Html', text: 'This is an app which I made by my own way - I did not copy it from any the tutorial!<br><br>Link to the demo is in github repository.', github: 'https://github.com/MagiTom/My-Wallet', details: '#' },
    { id: 9, name: 'Weather App', img: '../../../assets/img/apps/weather.png', img2:'../../../assets/img/apps/weather_s.png', img3:'../../../assets/img/apps/weather_s.png', video:'../../../assets/img/apps/weatherapp.webm', technology:'Javascript, OOP, CSS, Html', text: 'It was my first exercise in my front-end studies. The task was to create weather app for five days in a few cities using weather api. This version of app is desktop only.', github: 'https://github.com/MagiTom/My_weather_app', details: '#' },
  ];

  export const games:Card[] = [
    { id: 10, name: 'Bat And Dragon', img: '../../../assets/img/games/batAndDragon.png', img2:'../../../assets/img/games/batAndDragon_s.png', img3:'../../../assets/img/games/batAndDragon_s.png', video:'../../../assets/img/games/bat.webm', technology:'Javascript, OOP, CSS, Html', text: "This is a game which I created inspired by space invaders game. I added a possibility to move  within the frames of the window and shooting in all directions. Enemies are showing up from up side and left side of the board. I used JavaScript's classes to develop functionality of this game. This is a demo version with two levels, you have four lives. <br><br>Watch out for the UFO and the bat boss. The UFO will change into dragon when you shoot it down and it will attack you. To kill the bat boss you need to shoot it a couple times.", github: 'https://github.com/MagiTom/Bat-And-Dragon-Game', details: '#' },
    { id: 11, name: 'Cookies Memory Game', img: '../../../assets/img/games/cookiesMemory.png', img2:'../../../assets/img/games/cookiesMemory_s.png', img3:'../../../assets/img/games/cookiesMemory_s.png', video:'../../../assets/img/games/cookies.webm', technology:'Javascript, OOP, CSS, Html', text: 'This is second version of my cookies memory games. First version was written in a functional JavaScript. In this version I focus on object oriented programming.', github: 'https://github.com/MagiTom/Cookies-Memory-Game', details: '#' },
  ]